# Merged for all applications when global.secretStore.backend=kubernetes
secretStore:
  name: kubernetes-backend
  kind: ClusterSecretStore
e2eTest:
  remoteRef:
    key: config-demo
    property: secret
