{{- if eq .Values.global.secretStore.backend "kubernetes" }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: kubernetes-backend
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ dig "ocpExternalSecrets" "kubernetes" "remoteNamespace" "validated-patterns-secrets" .Values.AsMap }}
      server:
        url: {{ dig "ocpExternalSecrets" "kubernetes" "server" "url" "https://kubernetes.default" .Values.AsMap }}
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: {{ dig "ocpExternalSecrets" "rbac" "serviceAccount" "namespace" "external-secrets" .Values.AsMap }}
      auth:
        serviceAccount:
          name: {{ dig "ocpExternalSecrets" "rbac" "serviceAccount" "name" "ocp-external-secrets" .Values.AsMap }}
          namespace: {{ dig "ocpExternalSecrets" "rbac" "serviceAccount" "namespace" "external-secrets" .Values.AsMap }}
{{- end }}
