{{- if and (eq .Values.global.secretStore.backend "kubernetes") (eq (.Values.clusterGroup.isHubCluster | default true) true) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets
  namespace: {{ dig "ocpExternalSecrets" "kubernetes" "remoteNamespace" "validated-patterns-secrets" .Values.AsMap }}
subjects:
- kind: ServiceAccount
  name: {{ dig "ocpExternalSecrets" "rbac" "serviceAccount" "name" "ocp-external-secrets" .Values.AsMap }}
  namespace: {{ dig "ocpExternalSecrets" "rbac" "serviceAccount" "namespace" "external-secrets" .Values.AsMap }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-secrets
{{- end }}
